name: igdesign
channels:
  - pyg
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - pip
  - python==3.11.9
  - pytorch::pytorch>=2.0,<2.1
  - pytorch::pytorch-cuda=11.8
  - pandas>=2.0,<2.1
  - lightning>=2.0,<2.1
  - cytoolz>=0.12.3
  - einops>=0.8.0
  - hydra-core>=1.3.2
  - biopython>=1.84
  - datasets>=2.20.0
  - hmmer=3.3.2
  - anarci
  - pip:
    - huggingface_hub>=0.24.5
    - transformers>=4.42.4
    - torchtyping>=0.1.4
